.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH file_setattr 2 (date) "Linux man-pages (unreleased)"
.SH NAME
file_setattr \- set filesystem inode attributes
.SH SYNOPSIS
.nf
.BR "#include <linux/fcntl.h>" "      /* Definition of " AT_* " constants */"
.BR "#include <linux/fs.h>" "         /* Definition of " FILE_ATTR_* \
" and " FS_XFLAG_* " constants */"
.BR "#include <sys/syscall.h>" "      /* Definition of " SYS_* " constants */"
.B #include <unistd.h>
.P
.B long syscall(SYS_file_setattr,
.BI "               int " dirfd ", const char *" pathname ,
.BI "               struct file_attr *" fattr ", size_t " size ,
.BI "               unsigned int " flags );
.fi
.P
.IR Note :
glibc provides no wrapper for
.BR file_setattr (),
necessitating the use of
.BR syscall (2).
.SH DESCRIPTION
The
.BR file_setattr ()
system call sets filesystem inode attributes
on the file specified by
.IR pathname .
.P
This system call provides functionality similar to the
.B FS_IOC_FSSETXATTR
.BR ioctl (2)
operation,
but with the advantage that the file does not need to be opened.
By using a pathname instead of requiring an open file descriptor,
.BR file_setattr ()
can manipulate filesystem inode attributes
on all file types,
including special files (FIFOs, sockets, block devices, character devices)
where opening the file may have side effects or may not be possible.
With
.BR ioctl (2),
it is not always possible to obtain a file descriptor that refers
directly to the filesystem inode for special files.
.P
As with
.BR openat (2),
if
.I pathname
is relative,
then it is interpreted relative to the directory
referred to by the file descriptor
.I dirfd
(or the current working directory of the calling process,
if
.I dirfd
is the special value
.BR AT_FDCWD ).
If
.I pathname
is absolute,
then
.I dirfd
is ignored.
.P
The
.I fattr
argument is a pointer to a
.I file_attr
structure,
which specifies the attributes to set on the file.
This structure is described in
.BR file_attr (2type).
User-space applications should use
.B file_getattr(2)
to initialize
.I struct fattr
beforehand.
.P
The
.I size
argument specifies the size of the buffer pointed to by
.IR fattr .
The size indicates version of the structure in use, refer to
.B file_attr(2type)
for more information on versioning.
.P
The
.I flags
argument is a bit mask that can include zero or more of the following values:
.TP
.B AT_EMPTY_PATH
If
.I pathname
is an empty string,
operate on the file referred to by
.I dirfd
(which may have been obtained using the
.BR open (2)
.B O_PATH
flag).
In this case,
.I dirfd
can refer to any type of file,
not just a directory.
.TP
.B AT_SYMLINK_NOFOLLOW
If
.I pathname
is a symbolic link,
do not dereference it:
instead set attributes on the symbolic link itself.
By default (i.e., if this flag is not specified),
symbolic links are dereferenced.
.SH RETURN VALUE
On success,
zero is returned.
On error,
\-1 is returned,
and
.I errno
is set to indicate the error.
.SH ERRORS
.TP
.B E2BIG
.I size
is larger than
.BR PAGE_SIZE .
.TP
.B E2BIG
.I size
indicates the version which kernel doesn't support (the size is larger than the
kernel expects) and new fields are non-zero.
.TP
.B EACCES
Search permission is denied for one of the directories
in the path prefix of
.IR pathname .
(See also
.BR path_resolution (7).)
.TP
.B EBADF
.I pathname
is relative but
.I dirfd
is neither
.B AT_FDCWD
nor a valid file descriptor.
.TP
.B EBADF
.I pathname
is an empty string,
.B AT_EMPTY_PATH
was specified in
.IR flags ,
and
.I dirfd
is an invalid file descriptor.
.TP
.B EFAULT
.I pathname
or
.I fattr
is an invalid pointer.
.TP
.B EINVAL
Invalid flag specified in
.IR flags .
.TP
.B EINVAL
.I size
is smaller than
.BR FILE_ATTR_SIZE_VER0 .
.TP
.B EINVAL
Invalid combination of parameters provided in
.I fattr
for this type of file or filesystem.
.TP
.B ELOOP
Too many symbolic links encountered while resolving
.IR pathname .
.TP
.B ENAMETOOLONG
.I pathname
is too long.
.TP
.B ENOENT
A component of
.I pathname
does not exist,
or
.I pathname
is an empty string and
.B AT_EMPTY_PATH
was not specified in
.IR flags .
.TP
.B ENOMEM
Insufficient kernel memory was available.
.TP
.B ENOTDIR
A component of the path prefix of
.I pathname
is not a directory or,
.I pathname
is relative and
.I dirfd
is a file descriptor referring to a file other than a directory.
.TP
.B EOPNOTSUPP
The filesystem does not support setting attributes on this type of inode.
.TP
.B EPERM
The caller does not have the necessary permissions
to change the file attributes.
.TP
.B EROFS
The file is on a read-only filesystem.
.SH HISTORY
.SS Linux 6.17
This system call is introduced as a more flexible alternative to the
FS_IOC_FSSETXATTR
.BR ioctl (2)
which could work on any type of files.
.SH NOTES
This system call is designed to be extensible.
The
.I size
argument allows user-space applications to indicate
which version of the
.I file_attr
structure they are using,
enabling the kernel to support both old and new versions
of the structure simultaneously.
.P
If
.I size
is smaller than the structure size the kernel expects,
the kernel treats the missing fields as having zero values
(which is a no-op).
If
.I size
is larger than expected,
the kernel checks that all unknown (to the kernel) fields are zero;
if not,
the call fails with
.BR E2BIG .
.SH EXAMPLES
The program below demonstrates the use of
.BR file_setattr ()
to set the
.B FS_XFLAG_NODUMP
flag on a file.
.P
.in +4n
.EX
#include <fcntl.h>
#include <linux/fcntl.h>
#include <linux/fs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

#ifndef SYS_file_getattr
#define SYS_file_getattr 467
#endif

#ifndef SYS_file_setattr
#define SYS_file_setattr 468
#endif

int
main(int argc, char *argv[])
{
    struct file_attr fa = { 0 };
    int dfd;
    long ret;

    if (argc != 2) {
        fprintf(stderr, "Usage: %s <filename>\\n", argv[0]);
        exit(EXIT_FAILURE);
    }

    dfd = open(argv[1], O_RDONLY);
    if (dfd == \-1) {
        perror("open");
        exit(EXIT_FAILURE);
    }

    ret = syscall(SYS_file_getattr, dfd, "", &fa, sizeof(fa), AT_EMPTY_PATH);
    if (ret == \-1) {
        perror("file_getattr");
        exit(EXIT_FAILURE);
    }

    printf("Current flags: 0x%llx\\n", (unsigned long long)fa.fa_xflags);

    fa.fa_xflags |= FS_XFLAG_NODUMP;

    ret = syscall(SYS_file_setattr, dfd, "", &fa, sizeof(fa), AT_EMPTY_PATH);
    if (ret == \-1) {
        perror("file_setattr");
        exit(EXIT_FAILURE);
    }

    ret = syscall(SYS_file_getattr, dfd, "", &fa, sizeof(fa), AT_EMPTY_PATH);
    if (ret == \-1) {
        perror("file_getattr");
        exit(EXIT_FAILURE);
    }

    if (fa.fa_xflags & FS_XFLAG_NODUMP)
        printf("flags 0x%llx (NODUMP flag is set)\\n",
            (unsigned long long)fa.fa_xflags);

    exit(EXIT_SUCCESS);
}
.EE
.in
.SH SEE ALSO
.BR file_getattr (2),
.BR ioctl (2),
.BR ioctl_fs (2),
.BR openat (2),
.BR file_attr (2type),
.BR path_resolution (7)
