#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Stub script for generating API specifications collector
# This is a placeholder until the full implementation is available
#

cat << 'EOF'
// SPDX-License-Identifier: GPL-2.0
/*
 * Auto-generated API specifications collector (stub)
 * Generated by scripts/generate_api_specs.sh
 */

#include <linux/kernel_api_spec.h>

/* No API specifications collected yet */
EOF
