name: kernel-test
on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: true
      test:
        type: string
        required: true
      timeout_minutes:
        type: number
        default: 30

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ci

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: kernel-selftests-${{ inputs.arch }}

      - name: Extract artifacts
        run: |
          zstd -d -T0 kernel-selftests-${{ inputs.arch }}.tar.zst --stdout | \
            tar -xf -

      - name: Run ${{ inputs.test }} selftests
        uses: linux-fsdevel/vfs-ci/run-vmtest@main
        with:
          arch: ${{ inputs.arch }}
          kernel-test: ${{ inputs.test }}
          kernel-root: '.'
          # kbuild-output is local to the repo, extracted from the artifacts.
          kbuild-output: kbuild-output
        env:
          VMTEST_MEMORY: 4G
          VMTEST_NUM_CPUS: 2
          KSELFTEST_DIR: /mnt/vmtest/kselftest-install
          DENYLIST_DIR: /mnt/vmtest/ci/vmtest/configs
